### ISSUE TITLE
fake news

### ISSUE THREAD

**Issue by moneywithbots** [captaingreem/Skid-Scammers-list#2]
im not a scammer never been one offer a partial refund to people using my free version please revise this list theres no need to burn bridges

**Comment by moneywithbots** [comment]
backdoors have legit purposes other than scams its to control this script if it gets into the wild please consider revising your list its against githubs terms and services to bully people

**Comment by moneywithbots** [comment]
please consider my proposal you have nothing to lose

**Comment by captaingreem** [comment]
stop crying scammer, your name is here because you are a scammer
